### ISSUE TITLE
Ability to override snackbard background colours

### ISSUE THREAD

**Issue by IsabellaRey** [Yuvaleros/material-ui-dropzone#45]
We're already using snackbars in other parts of our app, and it would be great if we could style the material-ui-dropzone snackbars background colour to be what we want (so we can make it the same as in the rest of the app).

For example, our colour for success is not the green[600] used here

**Comment by TerjeNorderhaug** [comment]
Agree that the snackbar background colors shouldn't be hardcoded but rather customizable (preferably through the theme).

Meanwhile, here is a css patch you can use as a temporary work-around, modifying the success variant of the snackbar:

```css 
div[aria-describedby="client-snackbar"][class*=" SnackbarContentWrapper-success"] {
   background-color: gray;
}
```
